### ISSUE TITLE
Separate the wireframe and the mockup in Figma

### ISSUE THREAD

**Issue by unglazedstamp** [echo-swent/echo#153]

**Comment by octogradiste** [comment]
- [ ] Separate wireframes (login/register/tag selection) into separate page.
- [ ] Create the login/register screen mockup as in the app.
- [ ] Create a clean mock up page.
- [ ] Delete all unused pages.
- [ ] Create on full user flow and set it as default
- [ ] Delete all other user flows
- [ ] Update the mock up to match the app.
