### ISSUE TITLE
mockup to create an event

### ISSUE THREAD

**Issue by unglazedstamp** [echo-swent/echo#19]
figma for the event creation
see user flow 8 on figma

**Comment by unglazedstamp** [comment]
I have two questions:
1. What should be displayed when the save button is pressed ?
2. How a user should set the location (string, interactive map, list, ...) ?

**Comment by unglazedstamp** [comment]
Can someone review the design please ?
@Greenade @ntissieres

**Comment by violoncelloCH** [comment]
>     1. What should be displayed when the save button is pressed ?

The most logical thing to show when someone clicks save is the created event. So the extended bottom sheet showing the just created event.


>     2. How the location should be set by a user (string, interactive map, list, ...) ?

For storing the event location we need coordinates. I don't think people will enter those manually. If we allow for a string to be entered I don't know how this could be translated into an exact location. There are things like Nominatim which allow to parse an address and translate it into coordinates on a map, but for on-campus locations I feel that this would never allow for inserting a precise location. The only way to do this would be to get the precise information from the EPFL geodata service (e.g. room number -> exact location). 
As a first step, we could allow to do both: enter a location string (as the name of the location) and let the user select the location on the map.

**Comment by unglazedstamp** [comment]
> The most logical thing to show when someone clicks save is the created event. So the extended bottom sheet showing the just created event.
That seems right, but for now we don't have this screen in Figma design so I will just replace it with the non extended bottom sheet. However, with this solution, it's more painful to add multiple events in a row because each time an event is created the user will have to go back to the hamburger menu if he wants to add another one. This is probably an edge case but it could happen for some associations which organize a lot of events or recurring events.
> 
> For storing the event location we need coordinates. I don't think people will enter those manually. If we allow for a string to be entered I don't know how this could be translated into an exact location. There are things like Nominatim which allow to parse an address and translate it into coordinates on a map, but for on-campus locations I feel that this would never allow for inserting a precise location. The only way to do this would be to get the precise information from the EPFL geodata service (e.g. room number -> exact location). As a first step, we could allow to do both: enter a location string (as the name of the location) and let the user select the location on the map.
That's probably the most flexible solution, I will add a button for map selection in Figma.
Thanks for the good ideas.

**Comment by violoncelloCH** [comment]
> However, with this solution, it's more painful to add multiple events in a row because each time an event is created the user will have to go back to the hamburger menu if he wants to add another one. This is probably an edge case but it could happen for some associations which organize a lot of events or recurring events.

I agree that this is not a common use case; so I think we can ignore this for now...
