### ISSUE TITLE
state object which holds the current network state, for composables and repository

### ISSUE THREAD

**Issue by violoncelloCH** [echo-swent/echo#190]
current connectivity state: https://developer.android.com/develop/connectivity/network-ops/reading-network-state#instantaneous
callback registration on state change: https://developer.android.com/training/monitoring-device-state/connectivity-status-type
the capability we want to check: https://developer.android.com/reference/android/net/NetworkCapabilities#NET_CAPABILITY_INTERNET

**Comment by octogradiste** [comment]
Thanks for adding those links! I feel like we should check for the [NET_CAPABILITY_VALIDATED](https://developer.android.com/reference/android/net/NetworkCapabilities#NET_CAPABILITY_VALIDATED). As `NET_CAPABILITY_INTERNET` doesn't mean you can reach public servers...

Also, I've been thinking on how to implement this. I suggest something like this:

```kotlin
interface NetworkService {
    // Useful for the UI
    val isOnline: StateFlow<Boolean>

    // Useful for the Repository
    fun isOnline(): Boolean
}
```

It would be really easy to configure this as a singleton which we could inject with hilt in any part of our code which needs this information.

**Comment by unglazedstamp** [comment]
Good idea, you could rename the function `isOnlineNow()` to differentiate the function from the stateflow.
