### ISSUE TITLE
allow to subscribe/join to Events

### ISSUE THREAD

**Issue by violoncelloCH** [echo-swent/echo#192]
- [x] add relation in supabase
- [x] add a setter (and deleter) on the `RemoteDataSource` and figure out how to send the query to supabase
- [x] add relation to room
- [x] add a setter (and deleter) to `LocalDataSource`
- [x] add setter on `Repository`
- [ ] connect the button in the UI to it

**Comment by octogradiste** [comment]
I think this is something which the user can only do when he is online. Otherwise, we would have to synchronize when he is back online. 

I'll still implement this functionality in room, but only for caching, the repository should ensure that nothing is modified while the app is offline.
